name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2016
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
    - name: build
      run: |
        cd $GITHUB_WORKSPACE\HexEditor\projects\2003\
        msbuild HexEditor.vcxproj /m /p:configuration="Release" /p:platform="x64" /p:PlatformToolset="v141_xp"


